config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'index#dashboard', as: :authenticated_root
  end
  unauthenticated do
    root to: 'index#welcome', as: :unauthenticated_root
  end

  resources :categories
  resources :bank_accounts
  resources :transactions
  resources :savings_goals
  resources :budgets
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  
    def index
      @transactions = current_user.transactions
    end
  
    def show
    end
  
    def new
      @transaction = Transaction.new
    end
  
    def create
      @transaction = current_user.transactions.build(transaction_params)
      if @transaction.save
        redirect_to authenticated_root_path, notice: 'Transaction was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @transaction.update(transaction_params)
        redirect_to authenticated_root_path, notice: 'Transaction was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @transaction.destroy
      redirect_to transactions_path, notice: 'Transaction was successfully destroyed.'
    end
  
    private
  
    def set_transaction
      @transaction = current_user.transactions.find(params[:id])
    end
  
    def transaction_params
      params.require(:transaction).permit(:amount, :description, :date, :category_id, :bank_account_id)
    end
end
  

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
<div class="max-w-sm mx-auto">
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-5">
    <%= form.label :amount, 'Qauntia', class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :amount, step: 0.01, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-5">
    <%= form.label :description, 'Descrição', class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :description, class:"block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-5">
    <%= form.label :date, 'Data', class: "block text-white text-sm font-bold mb-2" %>
    <%= form.date_select :date, :order => [:day, :month, :year], class: "p-10" %>
  </div>

  <div class="mb-5">
    <%= form.label :category, class: "block text-white text-sm font-bold mb-2" %>
    <%= form.collection_select :category_id, current_user.categories, :id, :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-5">
    <%= form.label :bank_account, class: "block text-white text-sm font-bold mb-2" %>
    <%= form.collection_select :bank_account_id, current_user.bank_accounts, :id, :bank_name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar', class: "text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
  </div>
</div>
<% end %>

app/views/transactions/edit.html.erb
<section class="bg-[#101015] h-screen flex flex-col justify-around items-center">
  <h1 class="mb-5 text-center text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Editar Transferências</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Voltar', transactions_path, class:"text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
</section>

app/views/transactions/index.html.erb
<section class="bg-[#101015] h-screen flex flex-col justify-around items-center">
  <h1 class="mb-5 text-center text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Transferências</h1>
  <div class="relative container font-mono overflow-y-auto shadow-md sm:rounded-lg">
      <table class="md:w-full w-1/2 md:text-sm text-xs text-left rtl:text-right text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                  <th scope="col" class="px-6 py-3">
                      Quantia
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Descrição
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Date
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Categoria
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Banco
                  </th>
                  <th scope="col" class="px-6 py-3">
                      <span class="sr-only">Edit</span>
                  </th>
              </tr>
          </thead>
          <tbody>
          <% @transactions.each do |transaction| %>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                  <% if transaction.amount >= 0 %>
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-green-500">
                      <%= number_to_currency(transaction.amount) %>
                  </th>
                  <% else %>
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-red-500">
                      <%= number_to_currency(transaction.amount) %>
                  </th>
                  <% end %>
                  <td class="px-6 py-4">
                      <%= transaction.description %>
                  </td>
                  <td class="px-6 py-4">
                      <%= transaction.date.strftime("%d de %B de %Y") %>
                  </td>
                  <td class="px-6 py-4">
                      <%= transaction.category.name %>
                  </td>
                  <td class="px-6 py-4">
                      <%= transaction.bank_account.bank_name %>
                  </td>
                  <td class="px-6 py-4 text-right">
                      <%= link_to edit_transaction_path(transaction) do %>
                        <span class="material-symbols-outlined hover:text-sky-500">edit</span>
                      <% end %>
                      <%= link_to transaction, data: { turbo_method: :delete, turbo_confirm: "Você tem certeza?" } do %>
                        <span class="material-symbols-outlined hover:text-red-500">delete</span>
                      <% end %>
                  </td>
              </tr>
          <% end %>
          </tbody>
      </table>
  </div>
  <%= link_to 'Voltar', authenticated_root_path, class:"text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
</section>

app/views/transactions/new.html.erb
<section class="bg-[#101015] h-screen flex flex-col justify-around items-center">
  <h1 class="mb-5 text-center text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Nova Transferências</h1>
<%= render 'form', transaction: @transaction %>

<%= link_to 'Voltar', authenticated_root_path, class:"text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
</section>