config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'index#dashboard', as: :authenticated_root
  end
  unauthenticated do
    root to: 'index#welcome', as: :unauthenticated_root
  end

  resources :categories
  resources :bank_accounts
  resources :transactions
  resources :savings_goals
  resources :budgets
end

app/models/savings_goal.rb
class SavingsGoal < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :target_amount, presence: true, numericality: { greater_than: 0 }
  validates :current_amount, numericality: { greater_than_or_equal_to: 0 }
  validates :end_date, presence: true
end

app/controllers/savings_goals_controller.rb
class SavingsGoalsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_savings_goal, only: [:show, :edit, :update, :destroy]
  
    def index
      @savings_goals = current_user.savings_goals
    end
  
    def show
    end
  
    def new
      @savings_goal = SavingsGoal.new
    end
  
    def create
      @savings_goal = current_user.savings_goals.build(savings_goal_params)
      if @savings_goal.save
        redirect_to savings_goals_path, notice: 'Savings goal was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @savings_goal.update(savings_goal_params)
        redirect_to savings_goals_path, notice: 'Savings goal was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @savings_goal.destroy
      redirect_to savings_goals_path, notice: 'Savings goal was successfully destroyed.'
    end
  
    private
  
    def set_savings_goal
      @savings_goal = current_user.savings_goals.find(params[:id])
    end
  
    def savings_goal_params
      params.require(:savings_goal).permit(:name, :target_amount, :current_amount, :end_date)
    end
end
  

app/helpers/savings_goals_helper.rb
module SavingsGoalsHelper
end

app/views/savings_goals/_form.html.erb
<%= form_with(model: savings_goal, local: true) do |form| %>
  <% if savings_goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(savings_goal.errors.count, "error") %> prohibited this savings goal from being saved:</h2>

      <ul>
        <% savings_goal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :name, 'Nome', class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.label :target_amount, 'Valor Alvo', class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :target_amount, step: 0.01, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.label :current_amount, 'Valor Atual', class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :current_amount, step: 0.01, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.label :end_date, 'Data Final', class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar', class: "text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
  </div>
<% end %>

app/views/savings_goals/edit.html.erb
<section class="bg-[#101015] h-screen flex flex-col justify-around items-center">
    <h1 class="mb-5 text-center text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Editar Meta</h1>

    <%= render 'form', savings_goal: @savings_goal %>

    <%= link_to 'Voltar', savings_goals_path, class:"text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
</section>

app/views/savings_goals/index.html.erb
<section class="bg-[#101015] h-screen">
  <h1 class="mb-5 text-center text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Metas</h1>
<% if current_user.savings_goals.any? %>
<div class=" shadow-md rounded-lg">
    <table class="w-full table-fixed text-xs text-left rtl:text-right text-gray-500 dark:text-gray-400 font-sans">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Nome
                </th>
                <th scope="col" class="px-6 py-3">
                    Valor alvo
                </th>
                <th scope="col" class="px-6 py-3">
                    Valor atual
                </th>
                <th scope="col" class="px-6 py-3">
                    Data final
                </th>
                <th scope="col" class="px-6 py-3">
                    
                </th>
            </tr>
        </thead>
        <tbody>
        <% current_user.savings_goals.each do |goal| %>
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    <%= goal.name %>
                </th>
                <td class="px-6 py-4">
                    <%= number_to_currency(goal.target_amount) %>
                </td>
                <td class="px-6 py-4">
                    <%= number_to_currency(goal.current_amount) %>
                </td>
                <td class="px-6 py-4">
                    <%= goal.end_date.strftime("%d/%m/%Y") %>
                </td>
                <td class="px-6 py-4 flex justify-around">
                  <%= link_to edit_savings_goal_path(goal) do %>
                    <span class="material-symbols-outlined hover:text-sky-500">edit</span>
                  <% end %>
                  <%= link_to goal, data: { turbo_method: :delete, turbo_confirm: "Você tem certeza?" } do %>
                    <span class="material-symbols-outlined hover:text-red-500">delete</span>
                  <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
<% else %>
  <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
    <span class="font-medium">Atenção</span> Você não tem uma Metas cadastrada.
  </div>
<% end %>

<div class="md:p-5 px-2 py-5">
<%= link_to 'Voltar', authenticated_root_path, class:"text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
<%= link_to 'Nova Meta', new_savings_goal_path, class:"text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800 shadow-lg shadow-green-500/50 dark:shadow-lg dark:shadow-green-800/80 font-medium rounded-lg text-sm px-5 py-3 text-center" %>
</div>
</section>

app/views/savings_goals/new.html.erb
<section class="bg-[#101015] h-screen flex flex-col justify-around items-center">
    <h1 class="mb-5 text-center text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Nova Meta</h1>

    <%= render 'form', savings_goal: @savings_goal %>

    <%= link_to 'Voltar', savings_goals_path, class:"text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
</section>